## 1.	Write a Python Program to Add Two Matrices?

In [25]:
import numpy as np
mat1=np.matrix([[2,3],[3,4]])
mat2=np.matrix([[1,2],[2,3]])

In [26]:
mat1+mat2

matrix([[3, 5],
        [5, 7]])

## 2.	Write a Python Program to Multiply Two Matrices?

In [30]:
np.matmul(mat1,mat2)

matrix([[ 8, 13],
        [11, 18]])

## 3.	Write a Python Program to Transpose a Matrix?

In [31]:
np.transpose(mat1)

matrix([[2, 3],
        [3, 4]])

## 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [35]:
list_of_words=["ineuron","python","java","data"]
list_of_words.sort()
list_of_words

['data', 'ineuron', 'java', 'python']

## 5.	Write a Python Program to Remove Punctuation From a String?

In [61]:
class punctuation_remover:
    def __init__(self,string):
        self.string=string
    def remover(self):
        l=[]
        for chars in self.string:
            if chars.isalnum():
                l.append(chars)
        return "".join(l)

In [63]:
l=punctuation_remover("@qgfgfghgh__-we")
l.remover()

'qgfgfghghwe'